version: '3.8'

services:
  bot:
    build: ./bot
    env_file: .env
    depends_on:
      - db
    restart: always

  web:
    build: ./web
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ghost_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Karim_kiko1
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
